platform :ios, '16.0'

source 'https://cdn.cocoapods.org/'

target 'MentraExample' do
  use_frameworks!

  local_sdk_path = ENV['MENTRA_BLUETOOTH_SDK_LOCAL_PATH'] ||
    File.expand_path('../../../MentraOS/mobile/modules/bluetooth-sdk/ios', __dir__)

  pod 'MentraBluetoothSDK', :path => local_sdk_path
end
