platform :ios, '16.0'

source 'https://cdn.cocoapods.org/'

target 'MentraExample' do
  use_frameworks!

  local_sdk_path = ENV['MENTRA_BLUETOOTH_SDK_LOCAL_PATH'] ||
    '/Users/philippe/dev/MentraOS-philippe-os-1178-mentra-bluetooth-sdk/mobile/modules/bluetooth-sdk/ios'

  pod 'MentraBluetoothSDK', :path => local_sdk_path
end
